### ISSUE TITLE
Assignment complete

### ISSUE THREAD

**Issue by flochtililoch** [flochtililoch/rotten_tomatoes#1]
My app is complete, please review! /cc @codepathreview

**Comment by nickai** [comment]
:+1: Excellent work Florent! The point of this homework was to explore a simple example of a full MVC application with a RESTful API. A few notes after checking out the code:

* Nice code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you can take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
* Nice job adding visual polish to your app.
* Great to see you extend the details view and link to wikipedia!
* Nice work with the header files. You should always try to minimize the number of properties and methods in the header files and move all private properties and methods into the class extension (the @interface block in the .m file).
* Nice work implementing the Movie model.
* A good design is to have your custom Movie cell have a property `movie`. In the custom setter of `movie`, you can configure the various labels and images. This decouples your custom cells from the table view controllers.
* Nice work loading the images asynchronously.
* Nice work setting up the proper modes for the images so that they are not stretched.
* Nice work implementing the error message on network failure.

We have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_ios/feedback_guides_objc/project_1_feedback) which covers the most common points we see for this project. Read through the feedback guide point-by-point to determine other ways you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at <support@codepath.com>.
